services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: 'daily-diet'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the containers
      - '3306'
    volumes:
      - C:\Usuários\Desenvolvedor\mysql:\var\lib\mysql
